### ISSUE TITLE
Integrate ConfigMate with new Analyzer

### ISSUE THREAD

**Issue by ktminks** [ConfigMate/configmate-gui#41]
## Description

Current version of ConfigMate is functional and utilizes .cmrb rulebooks and .json configFiles. Integrate it into the current version of the VS Code extension and get a mostly functional, rough draft version running end-to-end without error. Prepare to deploy to production server (Marketplace).

This issue is limited to ConfigMate integration and data flow. Diagnostics and text highlighting are to be handled next, separately in #13.

## Tasks

- [x] ConfigMate runs locally from within this repo via CLI
- [x] Check button calls appropriate ConfigMate command
- [x] Check callback passes the correct filepath in the correct format
- [x] API calls are sent & received successfully
- [x] API response is correct, logged to debugger
- [x] .yml script to clone, build, and deploy
