### ISSUE TITLE
Deploy MVP

### ISSUE THREAD

**Issue by ktminks** [ConfigMate/configmate-gui#45]
## Description

Deploy the functional MVP to the Marketplace, and ensure it works as intended.

## Known bugs

1. Commands are not recognized in VS Code after installing from Marketplace. This may be a conflict with other extensions or built-in commands. It may be helpful to temporarily publish a simplified version of the extension with just the erroneous functionality to diagnose the issue.
2. ConfigMate sometimes doesn't shut down properly on VS Code close, so it runs in the background and is prevented from restarting when VS Code reopens.

## Tasks

- [x] Deployment script successful

In VS Code after installing from the Marketplace:
- ConfigMate:
  - [x] runs after install/startup
  - [ ] closes properly on VS Code close / reopens properly afterward
- [x] Commands are recognized and trigger correctly: **[Note: Look into just using functions for these]**
  - Rulebooks:
    - [x] **refresh**
    - [x] add
    - [x] delete
  - ConfigFiles:
    - [x] **refresh**
    - [x] **open**
  - ConfigMate:
    - [x] check
