### ISSUE TITLE
Enhance Diagnostic Feedback

### ISSUE THREAD

**Issue by ktminks** [ConfigMate/configmate-gui#46]
## Description

Enhance the diagnosticProvider to create a smoother user experience with more robust language support.

## Tasks

Research and implement the following improvements, wherever possible:
- [ ] Cache results so they will still display upon swapping editors, closing and reopening the file, etc.
- [ ] Provide 'Quick Fix' solutions
- [ ] TBD: Figure out other ways to improve the diagnostic feedback provided

Write tests to ensure accuracy:
- [ ] Should highlight errors in the correct location
- [ ] Should highlight errors in every file that they were found in
- [ ] Should highlight every error that was found in a file
- [ ] Should not highlight checks that passed
- [ ] Should retain error info when doc becomes inactive then active again
- [ ] Should retain error info when doc closes then opens again

## Resources

- [Diagnostics Tips & Tricks](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#diagnostics-tips-and-tricks)
- [Languages namespace documentation](https://code.visualstudio.com/api/references/vscode-api#languages)
- [Diagnostic object documentation](https://code.visualstudio.com/api/references/vscode-api#Diagnostic)
