### ISSUE TITLE
Adapt to server/client structure

### ISSUE THREAD

**Issue by ktminks** [ConfigMate/configmate-gui#50]
## Description

Refactor current project into a server/client structure. Ensure all previous features still function as intended.

## Tasks

- [x] Refactor into server/client structure 
- [x] Integrate API runtime into server 
- [ ] Integrate diagnostic feedback from API into new structure
- [ ] Tailor language server to rulebook language specification

## Resources

- [LSP Sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample)
- [Language server extension guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide)
- [Programmatic language features](https://code.visualstudio.com/api/language-extensions/programmatic-language-features)
